### ISSUE TITLE
没有任何使用说明文档吗？

### ISSUE THREAD

**Issue by shenkonghui** [longguikeji/arkid-core#13]

**Comment by welylongguikeji** [comment]
是需要产品说明文档，还是二次开发文档，或者接口文档？

**Comment by shenkonghui** [comment]
> 是需要产品说明文档，还是二次开发文档，或者接口文档？
需要产品说明文档，配置和操作手册之类，主要我想尝试一下，发现搭建好后，完全没有操作教程。如何接第三方应用，ldap或者oauth

**Comment by welylongguikeji** [comment]
> > 是需要产品说明文档，还是二次开发文档，或者接口文档？
> > 需要产品说明文档，配置和操作手册之类，主要我想尝试一下，发现搭建好后，完全没有操作教程。如何接第三方应用，ldap或者oauth

![image](https://user-images.githubusercontent.com/46774210/65314138-417a7f80-dbc8-11e9-9203-a785f0f01b0f.png)
管理后台-应用管理-添加应用
这里就可以配置协议参数

文档确实太少，开发任务重，后面慢慢补，有问题需求欢迎来扰

**Comment by shenkonghui** [comment]
> > > 是需要产品说明文档，还是二次开发文档，或者接口文档？
> > > 需要产品说明文档，配置和操作手册之类，主要我想尝试一下，发现搭建好后，完全没有操作教程。如何接第三方应用，ldap或者oauth
> 
> ![image](https://user-images.githubusercontent.com/46774210/65314138-417a7f80-dbc8-11e9-9203-a785f0f01b0f.png)
> 管理后台-应用管理-添加应用
> 这里就可以配置协议参数
> 
> 文档确实太少，开发任务重，后面慢慢补，有问题需求欢迎来扰

嗯嗯，界面上能操作的基本都能摸索出来..ldap功能似乎有问题，我尝试选择ldap是没有办法配置参数的，看了代码以后，发现需要更改配置文件，配置了以后，发现389端口没有开(应该是作为服务端吧..)。检查发现镜像里面的manager.py文件ldap模块被注释掉了，更改代码以后，重新打镜像，还是一样有问题。我准备放弃了

**Comment by welylongguikeji** [comment]
> > > > 是需要产品说明文档，还是二次开发文档，或者接口文档？
> > > > 需要产品说明文档，配置和操作手册之类，主要我想尝试一下，发现搭建好后，完全没有操作教程。如何接第三方应用，ldap或者oauth
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/46774210/65314138-417a7f80-dbc8-11e9-9203-a785f0f01b0f.png)
> > 管理后台-应用管理-添加应用
> > 这里就可以配置协议参数
> > 文档确实太少，开发任务重，后面慢慢补，有问题需求欢迎来扰
> 
> 嗯嗯，界面上能操作的基本都能摸索出来..ldap功能似乎有问题，我尝试选择ldap是没有办法配置参数的，看了代码以后，发现需要更改配置文件，配置了以后，发现389端口没有开(应该是作为服务端吧..)。检查发现镜像里面的manager.py文件ldap模块被注释掉了，更改代码以后，重新打镜像，还是一样有问题。我准备放弃了

-_-|| 我们这就修复下，再给次机会...

**Comment by skoogi** [comment]
您好 @shenkonghui 

请问您目前本地部署arkid的方式是？
1. 本地python运行   2. 单docker   3. 基于arkid-charts

关于LDAP
- 目前暂不支持配置参数
- LDAP的运行需要额外的镜像，正在整理中，稍后推到 dockerhub

除LDAP外，您存在困扰的地方还有？

**Comment by shenkonghui** [comment]
@skoogi  我是直接采用arkid-charts 在k8s上面安装的，主要我们公司内部账号会有oauth和ldap 2种协议，想打通所有的账号。
除了ldap，其他功能还没有怎么用。最好能够提供如何接入应用的说明，每个功能的操作说明+配图应该也是必须的

**Comment by skoogi** [comment]
[arkid-chart 0.1.1](https://github.com/longguikeji/arkid-charts/releases/download/0.1.1/arkid-0.1.1.tgz) 新版本已内置 LDAP，欢迎下载使用。

**Comment by shenkonghui** [comment]
@skoogi  
好的，测试了下ldap可用，但是有一点小BUG会存在不同步的情况(添加用户的时候,查看ldap数据库中没有新增用户，再次添加用户，用户全部同步过去了)。
oauth 2.0目前支持吗？

**Comment by skoogi** [comment]
@shenkonghui 
ldap的数据不是实时的，10min 同步一次

**Comment by skoogi** [comment]
关于 OAuth2.0，移步 #20
