### ISSUE TITLE
同步钉钉数据失败

### ISSUE THREAD

**Issue by maxoyed** [longguikeji/arkid-core#159]
无论是使用docker-compose还是手动部署，都无法同步钉钉数据，在请求`账号同步-钉钉账号-保存配置`接口时就会报`400`错误，后端日志如下：
```
Bad Request: /siteapi/oneid/config/
"PATCH /siteapi/oneid/config/ HTTP/1.1" 400 37
```

**Comment by ranran97390483** [comment]
> 无论是使用docker-compose还是手动部署，都无法同步钉钉数据，在请求`账号同步-钉钉账号-保存配置`接口时就会报`400`错误，后端日志如下：
> 
> ```
> Bad Request: /siteapi/oneid/config/
> "PATCH /siteapi/oneid/config/ HTTP/1.1" 400 37
> ```

请提供下您使用的前后端版本号，另外，您可通过直接调用后端接口来检查请求是否成功，以帮助我们快速定位问题所在。
