### ISSUE TITLE
来自QQ群，经典对白的问题

### ISSUE THREAD

**Issue by welylongguikeji** [longguikeji/arkid-core#174]
root@company:/data/k8s/office/arkid-charts/chart# helm install . --generate-name
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Certificate" in version "certmanager.k8s.io/v1alpha1"

请问 这种是什么原因  我看values里边没有生命类似的资源

![image](https://user-images.githubusercontent.com/46774210/84018716-e89b8300-a9b2-11ea-9b2a-19bcc221f909.png)

**Comment by skoogi** [comment]
Certificate 是用来申请证书的，需要 [cert-manager](https://cert-manager.io/docs/installation/kubernetes/) 的支持。

可以通过 `--set ingress.cert=false --set ingress.tls=false` 参数跳过
