### ISSUE TITLE
钉钉corpSecret 已经废弃了

### ISSUE THREAD

**Issue by lostz** [longguikeji/arkid-core#180]
钉钉corpSecret 已经废弃了,建议更新钉钉同步代码

**Comment by ranran97390483** [comment]
您在配置钉钉 corp_id 和 corp_secret 字段时，采用与 app_key 和 app_secret 相同的值即可；
例如，
{"ding_config":{"app_key": "123", "app_secret": "123456", "corp_id": "123" ,"corp_secret": "123456", "qr_app_id": "***","qr_app_secret":"***"}}

**Comment by lostz** [comment]
现在钉钉同步信息无法保存,报 Bad Request: /siteapi/oneid/config/

**Comment by ranran97390483** [comment]
尝试手动调一下 siteapi/oneid/task/import/ding/ 接口
