### ISSUE TITLE
同步钉钉账号功能无法保存配置

### ISSUE THREAD

**Issue by jiangzhen1002** [longguikeji/arkid-core#182]
账号管理-->账号同步-->钉钉账号，填入4个配置项后，点“保存配置”
/siteapi/oneid/config/ 400 Bad Request
请问是姿势不对，还是有bug？

**Comment by ranran97390483** [comment]
1、建议您尝试只针对某项进行配置，例如，只针对钉钉：
{"ding_config":{"app_key": "ding0qsuzgtnqs8jxwnd", "app_secret": "*****", "corp_id": "*****" ,"corp_secret": "*****", "qr_app_id": "****"}}
2、更直白一些，现在您需要在传递参数时留意
company_config['name_cn'] 
此项不可为空

**Comment by lostz** [comment]
我也遇到这个问题,没有明白这个要怎么操作,我只是刚初始化完系统,没有别的任何操作.

**Comment by lostz** [comment]
我也是这个问题,只是在后台配置,哪里能配置company_config 呀?

**Comment by Oo-RR-oO** [comment]
> 我也是这个问题,只是在后台配置,哪里能配置company_config 呀?

![image](https://user-images.githubusercontent.com/23496607/86778910-81deb780-c08d-11ea-8600-08c10a0c8ebe.png)
这个用到的是这个company_config字段

**Comment by Oo-RR-oO** [comment]
目前保存钉钉配置功能，ui需修复，我们将排期进行此bug的处理

**Comment by jiangzhen1002** [comment]
问题已解决，感谢！
