### ISSUE TITLE
配置邮箱时出错

### ISSUE THREAD

**Issue by welylongguikeji** [longguikeji/arkid-core#183]
![image](https://user-images.githubusercontent.com/46774210/84997906-b7287180-b181-11ea-8c93-e40afc4b9e06.png)

![image](https://user-images.githubusercontent.com/46774210/84997978-cf988c00-b181-11ea-8bde-157bed7b70a5.png)

**Comment by ranran97390483** [comment]
对应端口：
'smtp'：25
'smtps'：465
'msa'：587

**Comment by welylongguikeji** [comment]
我发现了，是QQ的问题，需要在QQ邮箱中把smtp服务打开，然后打开很费劲，打开了就好了

**Comment by ranran97390483** [comment]
ACK
