### ISSUE TITLE
注册账号类型设置 无法关闭

### ISSUE THREAD

**Issue by lostz** [longguikeji/arkid-core#184]
已经关闭了开放注册,为什么还要设置注册账号类型设置,如果没有邮箱和短信配置,就无法保存钉钉扫码登录,这个逻辑是不对的呀.

**Comment by ranran97390483** [comment]
1、UI展示问题，暂时可忽略（关闭开放注册,仍显示注册账号类型设置）
2、钉钉扫码配置总是可以保存，保存失败的原因很有可能是因为钉钉扫码配置信息不正确

**Comment by lostz** [comment]
真是一个很好的东西,但是现在就是没有文档,还有一些细节需要完善.

**Comment by ranran97390483** [comment]
ACK
