### ISSUE TITLE
login接口的token没返回过期时间

### ISSUE THREAD

**Issue by welylongguikeji** [longguikeji/arkid-core#185]
现在arkid在返回token的时候，没有携带token的有效期，感觉用http直接请求login接口，会导致在之后的鉴权活动要反复请求arkid来验证token是否有效，这个效率是不是不行？是不是应该在返回token的时候附带上有效期，在第三方应用自己的API就可以用这个有效期去验证token是否有效就好了？

**Comment by ranran97390483** [comment]
如果有必要的话，理论上是没有任何问题的。
更简便的，省略验证token，如果响应码为401，重新登录即可。
