### ISSUE TITLE
docker-compose up无法启动。 提示db权限错误

### ISSUE THREAD

**Issue by weijie199148** [longguikeji/arkid-core#188]
docker-compose up无法启动。 提示db权限错误

**Comment by Oo-RR-oO** [comment]
具体报错信息贴出来看下呢

**Comment by weijie199148** [comment]
rkid-db  | chown: changing ownership of '/var/lib/mysql/': Permission denied
arkid-ldap | 5f046a53 backend_startup_one (type=sql, suffix="dc=example,dc=org"): bi_db_open failed! (1)
arkid-ldap | 5f046a53 slapd stopped.
arkid-db  | chown: changing ownership of '/var/lib/mysql/': Permission denied
arkid-db exited with code 1
arkid-db  | chown: changing ownership of '/var/lib/mysql/': Permission denied
arkid-db exited with code 1
arkid-ldap | 5f046a57 backend_startup_one (type=sql, suffix="dc=example,dc=org"): bi_db_open failed! (1)
arkid-ldap | 5f046a57 slapd stopped.
arkid-ldap exited with code 1
arkid-ldap | 5f046a57 backend_startup_one (type=sql, suffix="dc=example,dc=org"): bi_db_open failed! (1)
arkid-ldap | 5f046a57 slapd stopped.
arkid-db  | chown: changing ownership of '/var/lib/mysql/': Permission denied
arkid-db exited with code 1

**Comment by weijie199148** [comment]
db 起不来。后面的项目就报错了

**Comment by weijie199148** [comment]
arkid-be  |     utility.execute()
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
arkid-be  |     self.fetch_command(subcommand).run_from_argv(self.argv)
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
arkid-be  |     self.execute(*args, **cmd_options)
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 361, in execute
arkid-be  |     self.check()
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
arkid-be  |     include_deployment_checks=include_deployment_checks,
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
arkid-be  |     issues = run_checks(tags=[Tags.database])
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
arkid-be  |     new_errors = check(app_configs=app_configs)
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/database.py", line 10, in check_database_backends
arkid-be  |     issues.extend(conn.validation.check(**kwargs))
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 9, in check
arkid-be  |     issues.extend(self._check_sql_mode(**kwargs))
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/validation.py", line 13, in _check_sql_mode
arkid-be  |     with self.connection.cursor() as cursor:
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 256, in cursor
arkid-be  |     return self._cursor()
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 233, in _cursor
arkid-be  |     self.ensure_connection()
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
arkid-be  |     self.connect()
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
arkid-be  |     raise dj_exc_value.with_traceback(traceback) from exc_value
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 217, in ensure_connection
arkid-be  |     self.connect()
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 195, in connect
arkid-be  |     self.connection = self.get_new_connection(conn_params)
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/django/db/backends/mysql/base.py", line 227, in get_new_connection
arkid-be  |     return Database.connect(**conn_params)
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
arkid-be  |     return Connection(*args, **kwargs)
arkid-be  |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 179, in __init__
arkid-be  |     super(Connection, self).__init__(*args, **kwargs2)
arkid-be  | django.db.utils.OperationalError: (2002, "Can't connect to MySQL server on 'arkid-db' (115)")
arkid-db exited with code 1
arkid-db  | chown: changing ownership of '/var/lib/mysql/': Permission denied

**Comment by Oo-RR-oO** [comment]
如果是centos7的话 关闭selinux试一下
