### ISSUE TITLE
oauth 2.0接入失败

### ISSUE THREAD

**Issue by shenkonghui** [longguikeji/arkid-core#20]
如图
![屏幕快照 2019-09-25 12.26.41.png](http://ww1.sinaimg.cn/large/654fc08fly1g7bnrul95sj20p30i4abf.jpg)
![屏幕快照 2019-09-25 12.36.00.png](http://ww1.sinaimg.cn/large/654fc08fly1g7bnr9dirtj20uk0hrac4.jpg)

**Comment by skoogi** [comment]
@shenkonghui  目前确实还不支持 password 模式，将在2天内实现。

我们内部使用的是 授权码 模式，您若接受的话可以试试。

另外，您这既然都需提供账号、密码了，是不是可以直接使用 [登录接口 /siteapi/v1/ucenter/login/](https://oneid1.docs.apiary.io/#reference/user-center/1/0) 呢？

**Comment by skoogi** [comment]
content-type 需使用 "application/x-www-form-urlencoded"
https://tools.ietf.org/html/rfc6749#section-4.3.2
