### ISSUE TITLE
[建议]管理员添加用户的流程

### ISSUE THREAD

**Issue by shenkonghui** [longguikeji/arkid-core#22]
目前管理员添加用户没有设置密码的选项，添加完账号还不能使用，必须让用户邀请激活，前提还必须配置好邮箱/手机进行验证。
感觉这个流程太复杂了吧，我只想简单的使用，并不想配置邮箱(邮箱服务器尝试配置一直提示失败)和电话..
建议管理员添加用户，直接设置密码，用户就可以直接进行登录了

**Comment by skoogi** [comment]
已支持
