### ISSUE TITLE
配置邮箱失败

### ISSUE THREAD

**Issue by shenkonghui** [longguikeji/arkid-core#23]
配置邮箱提示失败
控制台显示...看参数就安全不对呀.
request
```
{
access_key: "xxxx@xxx.com"
access_secret: "xxxx"
host: "smtp.qiye.aliyun.com"
port: 465
}
```
response
```
{"email":["invalid"]}
```
![屏幕快照 2019-09-25 19.08.09.png](http://ww1.sinaimg.cn/large/654fc08fly1g7bz6scwfaj20vq03xaan.jpg)

**Comment by skoogi** [comment]
参数是这样子没有问题的

目前还没有用阿里云邮箱测试过，我们需要测试下

**Comment by skoogi** [comment]
@shenkonghui  已支持，按截图中的配置即可
