### ISSUE TITLE
前后端部署完后，登录报错

### ISSUE THREAD

**Issue by chixianliangGithub** [longguikeji/arkid-core#94]
arkid-core\siteapi\v1\serializers\app.py 

saml_app = SAMLAPPSerializer(many=False, required=False) 
改为
saml_app = SAMLAPPSerializer(many=False, required=False, allow_null=True)
解决 saml_app  为空报错问题

**Comment by skoogi** [comment]
ACK

感谢，我们会尽快修复 @chixianliangGithub
